// This file is auto-generated by @hey-api/openapi-ts

export const SignInSchemaSchema = {
  type: ["object"],
  properties: {
    email: {
      type: ["string"],
    },
    password: {
      type: ["string"],
    },
  },
  required: ["email", "password"],
  title: "SignInSchema",
  description: "Schema for sign in",
} as const;

export const RegisterSchemaSchema = {
  type: ["object"],
  properties: {
    email: {
      type: ["string"],
    },
    username: {
      type: ["string"],
    },
    password: {
      type: ["string"],
    },
  },
  required: ["email", "username", "password"],
  title: "RegisterSchema",
  description: "Schema for register",
} as const;

export const CreateLinkSchemaSchema = {
  type: ["object"],
  properties: {
    url: {
      type: ["string"],
    },
  },
  required: ["url"],
  title: "CreateLinkSchema",
  description: "Schema for create link item",
} as const;

export const LinksSchemaSchema = {
  type: ["array"],
  items: {
    $ref: "#/components/schemas/LinkSchema",
  },
  title: "LinksSchema",
  description: "Schema for links",
} as const;

export const LinkSchemaSchema = {
  type: ["object"],
  properties: {
    id: {
      type: ["string"],
    },
    url: {
      type: ["string"],
    },
    createdAt: {
      type: ["string"],
      format: "date-time",
    },
    updatedAt: {
      type: ["string"],
      format: "date-time",
    },
  },
  required: ["id", "url", "createdAt", "updatedAt"],
  title: "LinkSchema",
  description: "Schema for link item",
} as const;
