// This file is auto-generated by @hey-api/openapi-ts

export const CreateLinkSchemaSchema = {
  type: ['object'],
  properties: {
    url: {
      type: ['string'],
    },
  },
  required: ['url'],
  title: 'CreateLinkSchema',
  description: 'Schema for create link item',
} as const;

export const LinksSchemaSchema = {
  type: ['array'],
  items: {
    $ref: '#/components/schemas/LinkSchema',
  },
  title: 'LinksSchema',
  description: 'Schema for links',
} as const;

export const LinkSchemaSchema = {
  type: ['object'],
  properties: {
    id: {
      type: ['string'],
    },
    url: {
      type: ['string'],
    },
    createdAt: {
      type: ['string'],
      format: 'date-time',
    },
    updatedAt: {
      type: ['string'],
      format: 'date-time',
    },
  },
  required: ['id', 'url', 'createdAt', 'updatedAt'],
  title: 'LinkSchema',
  description: 'Schema for link item',
} as const;
