// This file is auto-generated by @hey-api/openapi-ts

export const SignInSchemaSchema = {
  type: ["object"],
  properties: {
    email: {
      type: ["string"],
      format: "email",
    },
    password: {
      type: ["string"],
      minLength: 8,
    },
  },
  required: ["email", "password"],
  title: "SignInSchema",
  description: "Schema for sign in",
} as const;

export const RegisterSchemaSchema = {
  type: ["object"],
  properties: {
    email: {
      type: ["string"],
      format: "email",
    },
    username: {
      type: ["string"],
      minLength: 3,
    },
    password: {
      type: ["string"],
      minLength: 8,
    },
  },
  required: ["email", "username", "password"],
  title: "RegisterSchema",
  description: "Schema for register",
} as const;

export const CreateLinkSchemaSchema = {
  type: ["object"],
  properties: {
    url: {
      type: ["string"],
      format: "uri",
    },
    title: {
      type: ["string"],
    },
    description: {
      type: ["string"],
    },
  },
  required: ["url"],
  title: "CreateLinkSchema",
  description: "Schema for create link item",
} as const;

export const UpdateLinkSchemaSchema = {
  type: ["object"],
  properties: {
    url: {
      type: ["string"],
      format: "uri",
    },
    title: {
      type: ["string"],
      minLength: 2,
    },
    description: {
      type: ["string"],
    },
  },
  title: "UpdateLinkSchema",
  description: "Schema for update link item",
} as const;

export const SafeUserSchemaSchema = {
  type: ["object"],
  properties: {
    id: {
      type: ["string"],
    },
    email: {
      type: ["string"],
      format: "email",
    },
    username: {
      type: ["string"],
    },
  },
  required: ["id", "email", "username"],
  title: "SafeUserSchema",
  description: "Schema for safe user item",
} as const;

export const LinksSchemaSchema = {
  type: ["array"],
  items: {
    $ref: "#/components/schemas/LinkSchema",
  },
  title: "LinksSchema",
  description: "Schema for links",
} as const;

export const LinkSchemaSchema = {
  type: ["object"],
  properties: {
    id: {
      type: ["string"],
    },
    url: {
      type: ["string"],
    },
    title: {
      type: ["string"],
    },
    description: {
      type: ["string"],
    },
    image: {
      type: ["string"],
    },
    generated: {
      type: ["boolean"],
    },
    createdAt: {
      type: ["string"],
      format: "date-time",
    },
    updatedAt: {
      type: ["string"],
      format: "date-time",
    },
  },
  required: ["id", "url", "generated", "createdAt", "updatedAt"],
  title: "LinkSchema",
  description: "Schema for link item",
} as const;
