// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  LinksControllerGetAllLinksData,
  LinksControllerGetAllLinksResponses,
  LinksControllerCreateLinkData,
  LinksControllerCreateLinkResponses,
  AuthControllerSignInData,
  AuthControllerSignInResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerMeData,
  AuthControllerMeResponses,
} from "./types.gen";
import {
  linksControllerGetAllLinksResponseTransformer,
  linksControllerCreateLinkResponseTransformer,
} from "./transformers.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const linksControllerGetAllLinks = <
  ThrowOnError extends boolean = false
>(
  options?: Options<LinksControllerGetAllLinksData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    LinksControllerGetAllLinksResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: linksControllerGetAllLinksResponseTransformer,
    url: "/links",
    ...options,
  });
};

export const linksControllerCreateLink = <ThrowOnError extends boolean = false>(
  options: Options<LinksControllerCreateLinkData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    LinksControllerCreateLinkResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: linksControllerCreateLinkResponseTransformer,
    url: "/links",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const authControllerSignIn = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSignInData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerSignInResponses,
    unknown,
    ThrowOnError
  >({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    url: "/auth/logout",
    ...options,
  });
};

export const authControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerMeData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthControllerMeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/auth/me",
    ...options,
  });
};
