// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { LinksControllerGetAllLinksData, LinksControllerGetAllLinksResponses, LinksControllerCreateLinkData, LinksControllerCreateLinkResponses, LinksControllerDeleteLinkData, LinksControllerDeleteLinkResponses, LinksControllerUpdateLinkData, LinksControllerUpdateLinkResponses, AuthControllerSignInData, AuthControllerSignInResponses, AuthControllerRefreshTokenData, AuthControllerRefreshTokenResponses, AuthControllerRegisterData, AuthControllerRegisterResponses, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerMeData, AuthControllerMeResponses, TagsControllerGetAllTagsData, TagsControllerGetAllTagsResponses, TagsControllerCreateMultipleTagsData, TagsControllerCreateMultipleTagsResponses, TagsControllerGetAllPinnedTagsData, TagsControllerGetAllPinnedTagsResponses, TagsControllerDeletePinnedTagData, TagsControllerDeletePinnedTagResponses, TagsControllerCreatePinnedTagData, TagsControllerCreatePinnedTagResponses, TagsControllerDeleteTagData, TagsControllerDeleteTagResponses, TagsControllerUpdateTagData, TagsControllerUpdateTagResponses } from './types.gen';
import { linksControllerGetAllLinksResponseTransformer, linksControllerCreateLinkResponseTransformer, linksControllerUpdateLinkResponseTransformer } from './transformers.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const linksControllerGetAllLinks = <ThrowOnError extends boolean = false>(options?: Options<LinksControllerGetAllLinksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<LinksControllerGetAllLinksResponses, unknown, ThrowOnError>({
        responseTransformer: linksControllerGetAllLinksResponseTransformer,
        url: '/links',
        ...options
    });
};

export const linksControllerCreateLink = <ThrowOnError extends boolean = false>(options: Options<LinksControllerCreateLinkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LinksControllerCreateLinkResponses, unknown, ThrowOnError>({
        responseTransformer: linksControllerCreateLinkResponseTransformer,
        url: '/links',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const linksControllerDeleteLink = <ThrowOnError extends boolean = false>(options: Options<LinksControllerDeleteLinkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<LinksControllerDeleteLinkResponses, unknown, ThrowOnError>({
        url: '/links/{id}',
        ...options
    });
};

export const linksControllerUpdateLink = <ThrowOnError extends boolean = false>(options: Options<LinksControllerUpdateLinkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<LinksControllerUpdateLinkResponses, unknown, ThrowOnError>({
        responseTransformer: linksControllerUpdateLinkResponseTransformer,
        url: '/links/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const authControllerSignIn = <ThrowOnError extends boolean = false>(options: Options<AuthControllerSignInData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthControllerSignInResponses, unknown, ThrowOnError>({
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const authControllerRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AuthControllerRefreshTokenResponses, unknown, ThrowOnError>({
        url: '/auth/refresh',
        ...options
    });
};

export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthControllerRegisterResponses, unknown, ThrowOnError>({
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthControllerLogoutResponses, unknown, ThrowOnError>({
        url: '/auth/logout',
        ...options
    });
};

export const authControllerMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthControllerMeResponses, unknown, ThrowOnError>({
        url: '/auth/me',
        ...options
    });
};

export const tagsControllerGetAllTags = <ThrowOnError extends boolean = false>(options?: Options<TagsControllerGetAllTagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<TagsControllerGetAllTagsResponses, unknown, ThrowOnError>({
        url: '/tags',
        ...options
    });
};

export const tagsControllerCreateMultipleTags = <ThrowOnError extends boolean = false>(options: Options<TagsControllerCreateMultipleTagsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<TagsControllerCreateMultipleTagsResponses, unknown, ThrowOnError>({
        url: '/tags',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const tagsControllerGetAllPinnedTags = <ThrowOnError extends boolean = false>(options?: Options<TagsControllerGetAllPinnedTagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<TagsControllerGetAllPinnedTagsResponses, unknown, ThrowOnError>({
        url: '/tags/pinned',
        ...options
    });
};

export const tagsControllerDeletePinnedTag = <ThrowOnError extends boolean = false>(options: Options<TagsControllerDeletePinnedTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<TagsControllerDeletePinnedTagResponses, unknown, ThrowOnError>({
        url: '/tags/{tagId}/pin',
        ...options
    });
};

export const tagsControllerCreatePinnedTag = <ThrowOnError extends boolean = false>(options: Options<TagsControllerCreatePinnedTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<TagsControllerCreatePinnedTagResponses, unknown, ThrowOnError>({
        url: '/tags/{tagId}/pin',
        ...options
    });
};

export const tagsControllerDeleteTag = <ThrowOnError extends boolean = false>(options: Options<TagsControllerDeleteTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<TagsControllerDeleteTagResponses, unknown, ThrowOnError>({
        url: '/tags/{id}',
        ...options
    });
};

export const tagsControllerUpdateTag = <ThrowOnError extends boolean = false>(options: Options<TagsControllerUpdateTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<TagsControllerUpdateTagResponses, unknown, ThrowOnError>({
        url: '/tags/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};