// This file is auto-generated by @hey-api/openapi-ts

import type {
  LinksControllerGetAllLinksResponse,
  LinksControllerCreateLinkResponse,
  LinksControllerUpdateLinkResponse,
} from "./types.gen";

const linkSchemaSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const linksSchemaSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => {
    return linkSchemaSchemaResponseTransformer(item);
  });
  return data;
};

export const linksControllerGetAllLinksResponseTransformer = async (
  data: any
): Promise<LinksControllerGetAllLinksResponse> => {
  data = linksSchemaSchemaResponseTransformer(data);
  return data;
};

export const linksControllerCreateLinkResponseTransformer = async (
  data: any
): Promise<LinksControllerCreateLinkResponse> => {
  data = linkSchemaSchemaResponseTransformer(data);
  return data;
};

export const linksControllerUpdateLinkResponseTransformer = async (
  data: any
): Promise<LinksControllerUpdateLinkResponse> => {
  data = linkSchemaSchemaResponseTransformer(data);
  return data;
};
