// This file is auto-generated by @hey-api/openapi-ts

/**
 * SignInSchema
 * Schema for sign in
 */
export type SignInSchema = {
  email: string;
  password: string;
};

/**
 * RegisterSchema
 * Schema for register
 */
export type RegisterSchema = {
  email: string;
  username: string;
  password: string;
};

/**
 * CreateLinkSchema
 * Schema for create link item
 */
export type CreateLinkSchema = {
  url: string;
};

/**
 * LinksSchema
 * Schema for links
 */
export type LinksSchema = Array<LinkSchema>;

/**
 * LinkSchema
 * Schema for link item
 */
export type LinkSchema = {
  id: string;
  url: string;
  createdAt: Date;
  updatedAt: Date;
};

export type LinksControllerGetAllLinksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/links";
};

export type LinksControllerGetAllLinksResponses = {
  /**
   * Schema for links
   */
  200: LinksSchema;
};

export type LinksControllerGetAllLinksResponse =
  LinksControllerGetAllLinksResponses[keyof LinksControllerGetAllLinksResponses];

export type LinksControllerCreateLinkData = {
  /**
   * Schema for create link item
   */
  body: CreateLinkSchema;
  path?: never;
  query?: never;
  url: "/links";
};

export type LinksControllerCreateLinkResponses = {
  /**
   * Schema for link item
   */
  200: LinkSchema;
};

export type LinksControllerCreateLinkResponse =
  LinksControllerCreateLinkResponses[keyof LinksControllerCreateLinkResponses];

export type AuthControllerSignInData = {
  /**
   * Schema for sign in
   */
  body: SignInSchema;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthControllerSignInResponses = {
  201: unknown;
};

export type AuthControllerRegisterData = {
  /**
   * Schema for register
   */
  body: RegisterSchema;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthControllerRegisterResponses = {
  201: unknown;
};

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type AuthControllerLogoutResponses = {
  200: unknown;
};

export type ClientOptions = {
  baseUrl: string;
};
