// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreateLinkSchema
 * Schema for create link item
 */
export const zCreateLinkSchema = z.object({
    url: z.string()
});

/**
 * LinkSchema
 * Schema for link item
 */
export const zLinkSchema = z.object({
    id: z.string(),
    url: z.string(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime()
});

/**
 * LinksSchema
 * Schema for links
 */
export const zLinksSchema = z.array(zLinkSchema);

export const zLinksControllerGetAllLinksData = z.object({
    body: z.never().optional(),
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Schema for links
 */
export const zLinksControllerGetAllLinksResponse = zLinksSchema;

export const zLinksControllerCreateLinkData = z.object({
    body: zCreateLinkSchema,
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Schema for link item
 */
export const zLinksControllerCreateLinkResponse = zLinkSchema;