// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * SignInSchema
 * Schema for sign in
 */
export const zSignInSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

/**
 * RegisterSchema
 * Schema for register
 */
export const zRegisterSchema = z.object({
  email: z.string().email(),
  username: z.string().min(3),
  password: z.string().min(8),
});

/**
 * CreateLinkSchema
 * Schema for create link item
 */
export const zCreateLinkSchema = z.object({
  url: z.string(),
});

/**
 * LinkSchema
 * Schema for link item
 */
export const zLinkSchema = z.object({
  id: z.string(),
  url: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

/**
 * LinksSchema
 * Schema for links
 */
export const zLinksSchema = z.array(zLinkSchema);

export const zLinksControllerGetAllLinksData = z.object({
  body: z.never().optional(),
  headers: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Schema for links
 */
export const zLinksControllerGetAllLinksResponse = zLinksSchema;

export const zLinksControllerCreateLinkData = z.object({
  body: zCreateLinkSchema,
  headers: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Schema for link item
 */
export const zLinksControllerCreateLinkResponse = zLinkSchema;

export const zAuthControllerSignInData = z.object({
  body: zSignInSchema,
  headers: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zAuthControllerRegisterData = z.object({
  body: zRegisterSchema,
  headers: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zAuthControllerLogoutData = z.object({
  body: z.never().optional(),
  headers: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});
