// This file is auto-generated by @hey-api/openapi-ts

/**
 * CreateLinkSchema
 * Schema for create link item
 */
export type CreateLinkSchema = unknown;

/**
 * LinksSchema
 * Schema for links
 */
export type LinksSchema = unknown;

/**
 * LinkSchema
 * Schema for link item
 */
export type LinkSchema = unknown;

export type LinksControllerGetAllLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links';
};

export type LinksControllerGetAllLinksResponses = {
    /**
     * Schema for links
     */
    200: LinksSchema;
};

export type LinksControllerGetAllLinksResponse = LinksControllerGetAllLinksResponses[keyof LinksControllerGetAllLinksResponses];

export type LinksControllerCreateLinkData = {
    /**
     * Schema for create link item
     */
    body: CreateLinkSchema;
    path?: never;
    query?: never;
    url: '/links';
};

export type LinksControllerCreateLinkResponses = {
    /**
     * Schema for link item
     */
    200: LinkSchema;
};

export type LinksControllerCreateLinkResponse = LinksControllerCreateLinkResponses[keyof LinksControllerCreateLinkResponses];

export type ClientOptions = {
    baseUrl: string;
};