// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreateLinkSchema
 * Schema for create link item
 */
export const zCreateLinkSchema = z.unknown();

/**
 * LinksSchema
 * Schema for links
 */
export const zLinksSchema = z.unknown();

/**
 * LinkSchema
 * Schema for link item
 */
export const zLinkSchema = z.unknown();

export const zLinksControllerGetAllLinksData = z.object({
    body: z.never().optional(),
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Schema for links
 */
export const zLinksControllerGetAllLinksResponse = zLinksSchema;

export const zLinksControllerCreateLinkData = z.object({
    body: zCreateLinkSchema,
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Schema for link item
 */
export const zLinksControllerCreateLinkResponse = zLinkSchema;